name: Build SaC Project

on:
  workflow_call: # reusable workflow

jobs:
  Does_It_Build:
    runs-on: ubuntu-latest
    container: sacbase/sac-compiler:41ed2a07
    steps:
      - name: Get HEAD and submodules
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Configure
        run: |
          cmake -S . -B ./build
      - name: Build
        run: |
          cmake --build ./build -j2
